'use strict';

const { WorkloadModuleBase } = require('@hyperledger/caliper-core');
const fs = require('fs');
const path = require('path');

/**
 * Workload module for reading a device by ID.
 * Loads device IDs from device-ids.json (generated by extract_device_ids.sh).
 */
class GetDeviceWorkload extends WorkloadModuleBase {
    constructor() {
        super();
        this.txIndex = 0;
        this.deviceIds = [];
    }

    async initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext) {
        await super.initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext);

        // Load device IDs from JSON file
        const idsFile = path.join(__dirname, 'device-ids.json');
        if (fs.existsSync(idsFile)) {
            this.deviceIds = JSON.parse(fs.readFileSync(idsFile, 'utf8'));
        }

        // Fallback: legacy sequential IDs
        if (this.deviceIds.length === 0) {
            const maxId = roundArguments.maxDeviceId || 200;
            for (let i = 1; i <= maxId; i++) {
                this.deviceIds.push('device' + i);
            }
        }
    }

    async submitTransaction() {
        this.txIndex++;
        const deviceId = this.deviceIds[(this.txIndex - 1) % this.deviceIds.length];

        const args = {
            contractId: 'golifecycle',
            contractFunction: 'device:GetDevice',
            contractArguments: [deviceId],
            readOnly: true,
            timeout: 30
        };

        await this.sutAdapter.sendRequests(args);
    }
}

function createWorkloadModule() {
    return new GetDeviceWorkload();
}

module.exports.createWorkloadModule = createWorkloadModule;
