# Docker Compose for the Electricity Producer organization (Tier 2)
version: '3.7'

networks:
  go-platform:
    name: go-platform_network

services:
  couchdb.eproducer1:
    extends:
      file: ../base.yaml
      service: couchdb-base
    container_name: couchdb.eproducer1
    ports:
      - 7984:5984
    volumes:
      - couchdb.eproducer1:/opt/couchdb/data
    networks:
      - go-platform

  peer0.eproducer1.go-platform.com:
    extends:
      file: ../base.yaml
      service: peer-base
    container_name: peer0.eproducer1.go-platform.com
    environment:
      - CORE_PEER_ID=peer0.eproducer1.go-platform.com
      - CORE_PEER_ADDRESS=peer0.eproducer1.go-platform.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.eproducer1.go-platform.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eproducer1.go-platform.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eproducer1.go-platform.com:9051
      - CORE_PEER_LOCALMSPID=eproducer1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.eproducer1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/eproducer1.go-platform.com/peers/peer0.eproducer1.go-platform.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/eproducer1.go-platform.com/peers/peer0.eproducer1.go-platform.com/tls:/etc/hyperledger/fabric/tls
      - peer0.eproducer1.go-platform.com:/var/hyperledger/production
    ports:
      - 9051:9051
    depends_on:
      - couchdb.eproducer1
    networks:
      - go-platform

volumes:
  couchdb.eproducer1:
  peer0.eproducer1.go-platform.com:
