# Docker Compose for the Buyer organization (Tier 3)
version: '3.7'

networks:
  go-platform:
    name: go-platform_network

services:
  couchdb.buyer1:
    extends:
      file: ../base.yaml
      service: couchdb-base
    container_name: couchdb.buyer1
    ports:
      - 11984:5984
    volumes:
      - couchdb.buyer1:/opt/couchdb/data
    networks:
      - go-platform

  peer0.buyer1.go-platform.com:
    extends:
      file: ../base.yaml
      service: peer-base
    container_name: peer0.buyer1.go-platform.com
    environment:
      - CORE_PEER_ID=peer0.buyer1.go-platform.com
      - CORE_PEER_ADDRESS=peer0.buyer1.go-platform.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer1.go-platform.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer1.go-platform.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer1.go-platform.com:13051
      - CORE_PEER_LOCALMSPID=buyer1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.buyer1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/buyer1.go-platform.com/peers/peer0.buyer1.go-platform.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/buyer1.go-platform.com/peers/peer0.buyer1.go-platform.com/tls:/etc/hyperledger/fabric/tls
      - peer0.buyer1.go-platform.com:/var/hyperledger/production
    ports:
      - 13051:13051
    depends_on:
      - couchdb.buyer1
    networks:
      - go-platform

volumes:
  couchdb.buyer1:
  peer0.buyer1.go-platform.com:
