version: '3.7'
networks:
  go-platform:
    name: go-platform_network
services:
  couchdb.eissuer:
    extends:
      file: ../base.yaml
      service: couchdb-base
    container_name: couchdb.eissuer
    ports:
      - 5984:5984
    volumes:
      - couchdb.eissuer:/opt/couchdb/data
    networks:
      - go-platform
  peer0.eissuer.go-platform.com:
    extends:
      file: ../base.yaml
      service: peer-base
    container_name: peer0.eissuer.go-platform.com
    environment:
      - CORE_PEER_ID=peer0.eissuer.go-platform.com
      - CORE_PEER_ADDRESS=peer0.eissuer.go-platform.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.eissuer.go-platform.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eissuer.go-platform.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eissuer.go-platform.com:7051
      - CORE_PEER_LOCALMSPID=eissuerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.eissuer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/eissuer.go-platform.com/peers/peer0.eissuer.go-platform.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/eissuer.go-platform.com/peers/peer0.eissuer.go-platform.com/tls:/etc/hyperledger/fabric/tls
      - peer0.eissuer.go-platform.com:/var/hyperledger/production
    ports:
      - 7051:7051
    depends_on:
      - couchdb.eissuer
    networks:
      - go-platform
volumes:
  couchdb.eissuer:
  peer0.eissuer.go-platform.com:
